// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Note struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	Content     string    `json:"content"`
	CreatedAt   time.Time `json:"created_at"`
	LastUpdated time.Time `json:"last_updated"`
}

type User struct {
	ID        int64          `json:"id"`
	Uid       sql.NullString `json:"uid"`
	CreatedAt time.Time      `json:"created_at"`
}
