// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Note struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	Content     string    `json:"content"`
	CreatedAt   time.Time `json:"created_at"`
	LastUpdated time.Time `json:"last_updated"`
}

type ShareHistory struct {
	ID           int64     `json:"id"`
	OwnerID      int64     `json:"owner_id"`
	SharedID     int64     `json:"shared_id"`
	SharedNoteID int64     `json:"shared_note_id"`
	SharedAt     time.Time `json:"shared_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}
